# Generated by Django 4.1.5 on 2023-01-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Student'},
        ),
    ]
