# Generated by Django 4.1.5 on 2023-01-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0004_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='field',
            field=models.TextField(default='?'),
            preserve_default=False,
        ),
    ]
